name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v6.0.2

    - name: Cache
      uses: actions/cache@v5.0.2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml')}}

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v22
    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v13

    - name: Install and build
      run: nix develop github:magic0whi/dev_flake#node --command sh -c \
        'pnpm install && pnpm build'

    # --- GitHub Pages specific upload ---
    - name: Upload GitHub Pages artifact
      if: github.server_url == 'https://github.com'
      uses: actions/upload-pages-artifact@v4.0.0
      with:
        path: ./_book

    # --- Forgejo specific upload ---
    - name: Upload artifact for Forgejo
      if: github.server_url != 'https://github.com'
      # https://github.com/actions/upload-artifact/blob/e454baaac2be505c9450e11b8f3215c6fc023ce8/README.md#ghes-support
      uses: actions/upload-artifact@v3.2.2
      with:
        path: ./_book

  deploy-github:
    runs-on: ubuntu-latest
    needs: build
    if: github.server_url == 'https://github.com'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5

  deploy-forgejo:
    runs-on: ubuntu-latest
    needs: build
    if: github.server_url != 'https://github.com'
    steps:
      - name: Download artifact
        # https://github.com/actions/download-artifact/tree/484a0b528fb4d7bd804637ccb632e47a0e638317?tab=readme-ov-file#ghes-support
        uses: actions/download-artifact@v3.1.0
        with:
          path: ./_book

      # Deploy the built site to homelab's Caddy directory over SSH
      - name: Deploy to homelab's Caddy Server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: proteus-nuc.tailba6c3f.ts.net # Proteus-NUC Tailscale IP
          username: proteus
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "_book/"
          target: "/var/www/notebook/"
          # Strips the '_book/' folder name so contents go directly into the target
          strip_components: 1
