name: Build and Deploy
on: [push]
env:
  ARTIFACT_NAME: notebook-build
  DEPLOY_HOST: proteus-nuc.tailba6c3f.ts.net # Proteus-NUC
  DEPLOY_USER: proteus
  DEPLOY_ROOT: /srv/www
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v6.0.2

    - name: Cache
      uses: actions/cache@v5.0.2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml')}}

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v22

    - name: Magic Nix Cache
      if: github.server_url == 'https://github.com'
      uses: DeterminateSystems/magic-nix-cache-action@v13

    # Proteus' Nix Cache (For self-hosted runners like Forgejo/Gitea)
    - name: Proteus' Nix Cache
      if: github.server_url != 'https://github.com'
      run: |
        mkdir -p ~/.config/nix
        cat <<EOF >> ~/.config/nix/nix.conf
        extra-substituters = https://s3.proteus.eu.org/nix-cache/
        extra-trusted-public-keys = s3.proteus.eu.org-1:IxrRwk4uC5ittHeG9menkuajABnrX9cboEWwZz/m4+E=
        EOF

    - name: Install and build
      run: nix develop github:magic0whi/dev_flake#node --command sh -c \
        'pnpm install && pnpm build'

    # --- GitHub Pages specific upload ---
    - name: Upload GitHub Pages artifact
      if: github.server_url == 'https://github.com'
      uses: actions/upload-pages-artifact@v4.0.0
      with:
        path: ./_book

    # --- Forgejo specific upload ---
    - name: Upload artifact for Forgejo
      if: github.server_url != 'https://github.com'
      uses: ChristopherHX/gitea-upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./_book

  deploy-github:
    runs-on: ubuntu-latest
    needs: build
    if: github.server_url == 'https://github.com'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5

  deploy-forgejo:
    runs-on: ubuntu-latest
    needs: build
    if: github.server_url != 'https://github.com'
    steps:
      - name: Download artifact
        # https://github.com/actions/download-artifact/tree/484a0b528fb4d7bd804637ccb632e47a0e638317?tab=readme-ov-file#ghes-support
        uses: ChristopherHX/gitea-download-artifact@v8
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./_book

      # Deploy the built site to homelab's Caddy directory over SSH
      - name: Deploy to homelab's Caddy Server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "_book/"
          target: ${{ env.DEPLOY_ROOT }}
          # Strips the '_book/' folder name so contents go directly into the target
          strip_components: 1
