name: Build and Deploy
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4.1.7
    - name: Install (cache) and build
    - name: Cache
      uses: actions/cache@v4.0.2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock')}}
    - name: Install and build
      run: |
        yarn install && yarn link --cwd honkit-plugin-katex
        yarn run honkit build
    # - name: Deploy
      # uses: magic0whi/git
